kind: pipeline
type: docker
name: direct-deploy

steps:
  - name: build
    image: maven:3.9.8-eclipse-temurin-21
    commands:
      - mvn clean package -DskipTests
    when:
      event: [push, tag]

  - name: copy-jar
    image: appleboy/drone-scp
    settings:
      host:
        from_secret: ssh_host
      username:
        from_secret: ssh_username
      key:
        from_secret: ssh_key
      port: 22
      target: /opt/app/
      source:
        - target/*.jar
    when:
      event: [push, tag]
    depends_on: [build]

  - name: deploy-and-run
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: ssh_host
      username:
        from_secret: ssh_username
      key:
        from_secret: ssh_key
      port: 22
      script:
        - cd /opt/app
        # Останавливаем старую версию
        - echo "Stopping existing application..."
        - pkill -f "java -jar.*viewing" || true
        - sleep 5
        # Создаем необходимые директории
        - mkdir -p models
        - mkdir -p logs
        - mkdir -p config
        # Находим последний JAR файл
        - JAR_FILE=$(ls -t *.jar | head -1)
        - echo "Starting application: $JAR_FILE"
        # Запускаем приложение
        - nohup java -jar $JAR_FILE --server.port=2062 > logs/app.log 2>&1 &
        - echo "Waiting for application to start..."
        - sleep 10
        # Проверяем что приложение запустилось
        - ps aux | grep java
        - echo "Application logs:"
        - tail -30 logs/app.log
        - echo "Checking if application is responding..."
        - curl -f http://localhost:2062/actuator/health || echo "Health check failed, but continuing..."
        - echo "Deployment completed!"
    when:
      event: [push, tag]
    depends_on: [copy-jar]

trigger:
  branch:
    - main
    - master
  event:
    - push
    - tag