kind: pipeline
type: docker
name: direct-deploy

steps:
  - name: build
    image: maven:3.9.8-eclipse-temurin-21
    commands:
      - mvn clean package -DskipTests
    when:
      event: [push, tag, custom]

  - name: copy-jar
    image: appleboy/drone-scp
    settings:
      host:
        from_secret: ssh_host
      username:
        from_secret: ssh_username
      key:
        from_secret: ssh_key
      port: 22
      target: /opt/app/
      source:
        - target/*.jar
      strip_components: 0
    when:
      event: [push, tag, custom]
    depends_on: [build]

  - name: deploy-and-run
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: ssh_host
      username:
        from_secret: ssh_username
      key:
        from_secret: ssh_key
      port: 22
      script:
        - cd /opt/app
        - echo "Stopping existing application..."
        - pkill -f "java -jar" || true
        - sleep 3
        - mkdir -p models logs
        - JAR_FILE=$(ls -t *.jar | head -1)
        - echo "Starting application: $JAR_FILE"
        - nohup java -jar $JAR_FILE --server.port=2062 > logs/app.log 2>&1 &
        - echo "Waiting for application to start..."
        - sleep 10
        - echo "Application status:"
        - ps aux | grep java | grep -v grep
        - echo "Recent logs:"
        - tail -20 logs/app.log
        - echo "Deployment completed successfully!"
    when:
      event: [push, tag, custom]
    depends_on: [copy-jar]

trigger:
  branch:
    - main
    - master
  event:
    - push
    - tag
    - custom