kind: pipeline
type: docker
name: direct-deploy

trigger:
  branch:
    - main
    - master

steps:
  - name: build
    image: maven:3.9.8-eclipse-temurin-21
    commands:
      - mvn clean package -DskipTests

  - name: copy-jar
    image: appleboy/drone-scp
    settings:
      host:
        from_secret: ssh_host
      username:
        from_secret: ssh_user
      password:
        from_secret: ssh_password
      port: 22
      target: /opt/app/
      source:
        - target/*.jar
      strip_components: 1
    depends_on: [build]

  - name: debug-application
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: ssh_host
      username:
        from_secret: ssh_user
      password:
        from_secret: ssh_password
      port: 22
      script:
        - |
          echo "=== DEBUGGING APPLICATION ==="
          cd /opt/app
          
          # Останавливаем всё
          pkill -9 -f java || true
          sleep 3
          
          # Запускаем приложение НАПРЯМУЮ (не в фоне) чтобы увидеть ошибки
          echo "Starting application in foreground to see errors..."
          java -Xmx512m -jar ar-webapp-1.0.0.jar --server.port=2062
          
          # Эта команда выполнится только если приложение упадет
          echo "=== Application exited with code: $? ==="
    depends_on: [copy-jar]