kind: pipeline
type: docker
name: direct-deploy

trigger:
  branch:
    - main
    - master

steps:
  - name: build
    image: maven:3.9.8-eclipse-temurin-21
    commands:
      - mvn clean package -DskipTests

  - name: copy-jar
    image: appleboy/drone-scp
    settings:
      host:
        from_secret: ssh_host
      username:
        from_secret: ssh_user
      password:
        from_secret: ssh_password
      port: 22
      target: /opt/app/
      source:
        - target/*.jar
      strip_components: 1
    depends_on: [build]

  - name: emergency-cleanup
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: ssh_host
      username:
        from_secret: ssh_user
      password:
        from_secret: ssh_password
      port: 22
      script:
        - |
          echo "=== EMERGENCY DISK CLEANUP ==="
          echo "Current disk usage:"
          df -h
          
          # Быстрая очистка
          sudo docker system prune -af || echo "Docker cleanup skipped"
          sudo apt clean
          sudo journalctl --vacuum-time=1d
          sudo rm -rf /var/log/*.gz /var/log/*.old
          sudo find /tmp -type f -atime +1 -delete 2>/dev/null || true
          
          echo "Disk after emergency cleanup:"
          df -h
    depends_on: [copy-jar]

  - name: deploy-minimal
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: ssh_host
      username:
        from_secret: ssh_user
      password:
        from_secret: ssh_password
      port: 22
      script:
        - |
          echo "=== Deploying with minimal resources ==="
          cd /opt/app
          
          # Останавливаем всё
          pkill -f "java.*jar" || true
          sleep 5
          
          # Создаем минимальные директории
          mkdir -p models logs
          
          # Запускаем с абсолютным минимумом памяти
          echo "Starting application..."
          nohup java -Xms32m -Xmx128m -jar ar-webapp-1.0.0.jar --server.port=2062 > logs/app.log 2>&1 &
          APP_PID=$!
          echo "PID: $APP_PID"
          
          # Даем больше времени на запуск из-за нехватки места
          sleep 30
          
          if ps -p $APP_PID > /dev/null; then
            echo "✅ SUCCESS: Application running!"
            echo "Memory usage:"
            ps -p $APP_PID -o pid,vsz,rss,pcpu,comm
            echo "Final disk status:"
            df -h
          else
            echo "❌ FAILED: Application died"
            echo "=== Last 100 lines of logs ==="
            tail -100 logs/app.log
            echo "=== Checking system resources ==="
            free -h
            df -h
            exit 1
          fi
    depends_on: [emergency-cleanup]